# Paste your exact Google Sheet publish link below
DATA_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vR489DyzPokngjN2hsZL8_wEML49n2oXjrptHteBNGo_4j9lpfkxt9KqOSOMb7Nkvqn4_1YpGfubMa0/pub?gid=0&single=true&output=csv"